name: Build and deploy Jekyll site

on:
  push:
    branches:
      - jekyll
  # Add this to make it the default workflow for Pages
  workflow_dispatch:
  page_build:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      
      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local frozen false
          
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - run: npm install
      
      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
